In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [3]:
def roc_auc():
    return roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovo')

In [4]:
df = pd.read_csv("chemberta_idotdo_MLM.csv" , index_col=0)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,...,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383
0,0.494268,0.118459,0.120281,0.582558,-0.301724,-0.248270,0.390228,0.199377,-0.209512,-0.093487,0.430537,-0.070625,0.633610,0.052689,-0.474021,0.110040,0.437953,-0.072735,-0.305195,-0.169478,0.139478,-0.148692,-0.520621,0.071848,-0.452346,-0.152098,0.233027,-0.055418,-0.187933,0.377597,-0.018959,0.521375,0.379857,-0.081417,0.179712,-0.345267,0.098250,0.197577,0.052971,0.267625,...,-0.253823,0.446424,0.250224,-0.199522,-0.344592,0.864495,-0.719822,0.087900,-0.258521,-0.066331,0.074562,0.137731,0.102823,-0.111381,-0.169864,0.171176,0.147298,-0.013902,0.151849,-0.329643,0.057343,-0.003587,-0.256406,0.289549,-0.178592,0.129052,0.007414,0.275624,-0.083670,0.039190,0.273344,-0.034014,-0.264945,0.181101,0.170081,-0.591491,0.241762,0.492498,-0.248157,-0.081414
1,0.005436,-0.024954,0.233959,0.497118,-0.151142,0.150918,0.206057,0.158802,0.084643,0.377474,0.019623,0.107397,-0.188241,-0.544617,-0.257098,0.038857,0.091887,0.183374,-0.182326,-0.243761,0.088488,-0.261139,-0.011586,-0.241629,0.370471,0.319166,-0.169925,-0.141755,-0.030749,-0.343973,0.181274,-0.086236,0.024701,0.209000,0.219688,-0.051550,-0.185428,0.078516,-0.181709,-0.140428,...,0.124657,-0.121376,0.122489,-0.011660,0.038167,0.251420,0.335942,0.041056,-0.295307,0.519698,0.060466,0.052495,0.103640,0.141098,-0.109517,0.188089,-0.048682,0.020817,0.222022,0.098723,-0.194010,-0.481618,-0.141250,0.221079,-0.038906,-0.313960,0.120246,0.197497,0.014052,0.027918,-0.313733,0.401681,0.357527,0.083439,0.127597,0.567946,-0.214001,-0.089507,-0.657648,-0.510167
2,0.428353,0.077683,0.119967,0.572152,-0.296688,-0.288362,0.366442,0.203296,-0.137712,-0.136954,0.454591,-0.056251,0.653111,0.120924,-0.441742,0.110902,0.452262,-0.100457,-0.313777,-0.176569,0.165241,-0.166504,-0.493284,0.074786,-0.452839,-0.154666,0.216822,-0.021109,-0.172538,0.329804,-0.026405,0.580952,0.402590,-0.056522,0.192328,-0.363344,0.154186,0.164569,0.025274,0.274237,...,-0.266861,0.448733,0.276857,-0.188701,-0.331062,0.843710,-0.662664,0.118448,-0.249052,-0.103706,0.071041,0.133424,0.096807,-0.120811,-0.165366,0.150009,0.170721,-0.021860,0.096412,-0.376085,0.099164,-0.007236,-0.242993,0.338205,-0.154496,0.124570,-0.059547,0.277287,-0.123650,0.041063,0.293401,-0.020694,-0.274401,0.165714,0.112009,-0.583639,0.235649,0.502577,-0.285817,-0.060027
3,-0.220455,-0.173326,0.087070,0.357093,-0.054140,0.141931,-0.005703,0.279797,0.166914,0.378540,0.356141,0.221647,0.029248,-0.497185,-0.424171,-0.031999,0.443394,-0.049796,-0.353229,0.117221,0.285133,-0.110942,-0.053847,-0.332566,0.086960,0.019598,0.044114,-0.155665,-0.318675,-0.309969,0.507899,0.081113,-0.205839,0.029542,0.146860,-0.412474,-0.110728,-0.005806,-0.404071,-0.091982,...,0.546689,-0.435413,0.022485,-0.030615,-0.033613,0.019371,0.260781,-0.331146,-0.078888,-0.440929,0.328806,0.304061,0.387457,0.303132,0.010825,-0.033151,0.294747,0.242938,0.359700,-0.017858,-0.029570,-0.402576,0.009077,-0.035128,0.117634,-0.033879,0.384822,0.010025,-0.160055,0.082692,-0.091736,0.205081,0.203580,0.118018,-0.133505,0.688311,-0.282882,0.161007,-0.621344,-0.184317
4,0.191558,0.217486,0.072423,-0.369289,-0.139498,-0.001433,0.266710,0.316668,-0.100810,0.161753,0.430044,0.054562,0.251701,0.079859,0.377849,0.837505,0.251651,0.149796,0.357829,-0.147596,0.032410,-0.094918,-0.432318,0.227943,-0.203412,0.116015,0.142662,0.061307,0.182021,0.020697,0.015006,0.651952,-0.353138,-0.651817,0.257730,-0.150864,0.382664,0.002160,0.174781,0.364000,...,-0.399509,0.244871,0.328338,0.224635,-0.128661,0.378712,0.032690,0.099470,0.007760,0.204616,0.137842,-0.005673,0.003266,-0.157576,-0.095425,-0.194538,-0.252499,0.091510,0.246260,-0.288065,0.360023,0.328907,-0.047441,-0.160079,-0.263188,0.544022,0.322365,-0.144147,-0.196061,-0.050705,0.185053,0.2

In [5]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

,ido_tdo
0,AA
1,II
2,AI
3,II
4,II
...,...
755,II
756,II
757,IA
758,AI


In [6]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [7]:
X = df.iloc[:, :]
X

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,...,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383
0,0.494268,0.118459,0.120281,0.582558,-0.301724,-0.248270,0.390228,0.199377,-0.209512,-0.093487,0.430537,-0.070625,0.633610,0.052689,-0.474021,0.110040,0.437953,-0.072735,-0.305195,-0.169478,0.139478,-0.148692,-0.520621,0.071848,-0.452346,-0.152098,0.233027,-0.055418,-0.187933,0.377597,-0.018959,0.521375,0.379857,-0.081417,0.179712,-0.345267,0.098250,0.197577,0.052971,0.267625,...,-0.253823,0.446424,0.250224,-0.199522,-0.344592,0.864495,-0.719822,0.087900,-0.258521,-0.066331,0.074562,0.137731,0.102823,-0.111381,-0.169864,0.171176,0.147298,-0.013902,0.151849,-0.329643,0.057343,-0.003587,-0.256406,0.289549,-0.178592,0.129052,0.007414,0.275624,-0.083670,0.039190,0.273344,-0.034014,-0.264945,0.181101,0.170081,-0.591491,0.241762,0.492498,-0.248157,-0.081414
1,0.005436,-0.024954,0.233959,0.497118,-0.151142,0.150918,0.206057,0.158802,0.084643,0.377474,0.019623,0.107397,-0.188241,-0.544617,-0.257098,0.038857,0.091887,0.183374,-0.182326,-0.243761,0.088488,-0.261139,-0.011586,-0.241629,0.370471,0.319166,-0.169925,-0.141755,-0.030749,-0.343973,0.181274,-0.086236,0.024701,0.209000,0.219688,-0.051550,-0.185428,0.078516,-0.181709,-0.140428,...,0.124657,-0.121376,0.122489,-0.011660,0.038167,0.251420,0.335942,0.041056,-0.295307,0.519698,0.060466,0.052495,0.103640,0.141098,-0.109517,0.188089,-0.048682,0.020817,0.222022,0.098723,-0.194010,-0.481618,-0.141250,0.221079,-0.038906,-0.313960,0.120246,0.197497,0.014052,0.027918,-0.313733,0.401681,0.357527,0.083439,0.127597,0.567946,-0.214001,-0.089507,-0.657648,-0.510167
2,0.428353,0.077683,0.119967,0.572152,-0.296688,-0.288362,0.366442,0.203296,-0.137712,-0.136954,0.454591,-0.056251,0.653111,0.120924,-0.441742,0.110902,0.452262,-0.100457,-0.313777,-0.176569,0.165241,-0.166504,-0.493284,0.074786,-0.452839,-0.154666,0.216822,-0.021109,-0.172538,0.329804,-0.026405,0.580952,0.402590,-0.056522,0.192328,-0.363344,0.154186,0.164569,0.025274,0.274237,...,-0.266861,0.448733,0.276857,-0.188701,-0.331062,0.843710,-0.662664,0.118448,-0.249052,-0.103706,0.071041,0.133424,0.096807,-0.120811,-0.165366,0.150009,0.170721,-0.021860,0.096412,-0.376085,0.099164,-0.007236,-0.242993,0.338205,-0.154496,0.124570,-0.059547,0.277287,-0.123650,0.041063,0.293401,-0.020694,-0.274401,0.165714,0.112009,-0.583639,0.235649,0.502577,-0.285817,-0.060027
3,-0.220455,-0.173326,0.087070,0.357093,-0.054140,0.141931,-0.005703,0.279797,0.166914,0.378540,0.356141,0.221647,0.029248,-0.497185,-0.424171,-0.031999,0.443394,-0.049796,-0.353229,0.117221,0.285133,-0.110942,-0.053847,-0.332566,0.086960,0.019598,0.044114,-0.155665,-0.318675,-0.309969,0.507899,0.081113,-0.205839,0.029542,0.146860,-0.412474,-0.110728,-0.005806,-0.404071,-0.091982,...,0.546689,-0.435413,0.022485,-0.030615,-0.033613,0.019371,0.260781,-0.331146,-0.078888,-0.440929,0.328806,0.304061,0.387457,0.303132,0.010825,-0.033151,0.294747,0.242938,0.359700,-0.017858,-0.029570,-0.402576,0.009077,-0.035128,0.117634,-0.033879,0.384822,0.010025,-0.160055,0.082692,-0.091736,0.205081,0.203580,0.118018,-0.133505,0.688311,-0.282882,0.161007,-0.621344,-0.184317
4,0.191558,0.217486,0.072423,-0.369289,-0.139498,-0.001433,0.266710,0.316668,-0.100810,0.161753,0.430044,0.054562,0.251701,0.079859,0.377849,0.837505,0.251651,0.149796,0.357829,-0.147596,0.032410,-0.094918,-0.432318,0.227943,-0.203412,0.116015,0.142662,0.061307,0.182021,0.020697,0.015006,0.651952,-0.353138,-0.651817,0.257730,-0.150864,0.382664,0.002160,0.174781,0.364000,...,-0.399509,0.244871,0.328338,0.224635,-0.128661,0.378712,0.032690,0.099470,0.007760,0.204616,0.137842,-0.005673,0.003266,-0.157576,-0.095425,-0.194538,-0.252499,0.091510,0.246260,-0.288065,0.360023,0.328907,-0.047441,-0.160079,-0.263188,0.544022,0.322365,-0.144147,-0.196061,-0.050705,0.185053,0.2

In [8]:
X_scaled = StandardScaler().fit_transform(X)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, stratify=y, random_state=42 , test_size=0.2)

In [10]:
# using default values

clf = KNeighborsClassifier()

In [11]:
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [14]:
ypred = clf.predict(X_test)

In [16]:
print("knn chemberta mlm")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
roc_auc()

knn chemberta mlm
              precision    recall  f1-score   support

          AA       0.53      0.74      0.62        42
          AI       0.67      0.71      0.69        34
          IA       0.50      0.25      0.33        16
          II       0.80      0.67      0.73        60

    accuracy                           0.65       152
   macro avg       0.63      0.59      0.59       152
weighted avg       0.67      0.65      0.65       152

[[31  6  2  3]
 [ 6 24  0  4]
 [ 8  1  4  3]
 [13  5  2 40]]


np.float64(0.7852092573140368)

In [17]:
# using default values

clf = KNeighborsClassifier(weights='distance')

In [18]:
clf.fit(X_train, y_train)

KNeighborsClassifier(weights='distance')

In [19]:
ypred = clf.predict(X_test)

In [20]:
print("knn chemberta mtr weight = distance")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
roc_auc()

knn chemberta mtr weight = distance
              precision    recall  f1-score   support

          AA       0.62      0.76      0.68        42
          AI       0.78      0.74      0.76        34
          IA       0.33      0.19      0.24        16
          II       0.78      0.77      0.77        60

    accuracy                           0.70       152
   macro avg       0.63      0.61      0.61       152
weighted avg       0.69      0.70      0.69       152

[[32  4  3  3]
 [ 5 25  0  4]
 [ 7  0  3  6]
 [ 8  3  3 46]]


np.float64(0.779175055438842)