In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [2]:
def roc_auc():
    return roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovo')

In [3]:
df = pd.read_csv("chemberta_idotdo_MTR.csv" , index_col=0)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,...,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383
0,0.098624,0.042223,-0.195243,0.209923,0.247522,-0.200116,0.130730,-0.078926,0.217784,-0.182055,-0.243452,-0.128551,0.014992,-0.187308,0.053134,0.172175,-0.036908,-0.089108,-0.158612,-0.175576,-0.147074,-0.137237,-0.023383,0.108736,0.110490,0.004352,0.199632,0.011544,0.247783,-0.131144,0.109549,-0.070373,0.081693,-0.004889,-0.073790,-0.009500,0.059168,-0.002304,0.099423,0.048033,...,0.397744,-0.058151,-0.222994,0.092650,0.015347,0.032601,-0.091596,-0.074980,0.016671,-0.099167,-0.033809,-0.046643,0.097833,0.106437,-0.127700,0.059653,0.046211,0.074801,0.136948,-0.043351,-0.009736,-0.101223,0.185495,0.222686,0.059982,0.096653,-0.290814,-0.072308,-0.047291,0.006758,-0.083785,-0.015257,0.208670,-0.099257,0.036652,0.011307,-0.015858,-0.034473,0.080340,0.090633
1,-0.195444,-0.006335,-0.125551,0.019175,-0.001245,-0.109488,0.118288,-0.345516,0.020197,-0.318505,-0.141652,-0.048505,0.051438,0.034231,-0.122795,0.134627,-0.019914,-0.224499,-0.282507,-0.006148,-0.334462,-0.077100,-0.352900,0.055391,-0.212135,0.235492,-0.005695,0.133163,0.104491,0.059605,-0.091889,-0.022493,-0.080808,0.118817,-0.063694,0.011782,-0.091441,0.021352,0.110410,-0.143980,...,0.105683,-0.098958,-0.164804,0.181757,0.200215,0.131650,0.201978,-0.216698,0.093964,-0.252054,0.098262,0.218040,-0.117740,-0.049576,0.287742,-0.153696,0.046452,-0.258802,-0.081757,0.196237,-0.283892,-0.056500,-0.063211,-0.007607,0.152183,-0.060643,-0.120640,-0.170838,0.012279,-0.124035,0.153339,-0.094293,0.072913,-0.126550,0.012802,-0.071275,0.245102,-0.169543,-0.080592,-0.355988
2,0.019954,0.011441,-0.158951,0.221017,0.246666,-0.214977,0.122784,-0.182540,0.290653,-0.235725,-0.271289,-0.122554,-0.024561,-0.165006,-0.047482,0.159697,-0.058642,-0.074084,-0.080705,-0.149393,-0.017351,-0.190900,-0.089300,0.130871,0.076236,-0.018202,0.064863,-0.064457,0.177324,-0.211699,0.038209,-0.179710,0.093308,-0.010702,-0.032118,0.066284,0.135030,-0.061713,0.082640,0.077583,...,0.363758,-0.120710,-0.277370,0.038140,0.104058,0.149905,-0.056109,-0.123888,0.014444,-0.059703,-0.029003,0.018654,0.167570,0.117122,-0.128163,-0.022087,0.023782,0.038430,0.181735,-0.018521,0.023721,-0.101120,0.183844,0.269394,-0.006547,0.232654,-0.292566,0.036904,-0.010980,-0.045801,-0.117349,-0.072634,0.212387,0.004530,-0.039211,-0.015519,0.015888,-0.153794,0.055760,0.118594
3,0.208809,0.168003,-0.015691,-0.009882,0.152641,0.031507,-0.038857,-0.054616,0.173442,-0.060251,-0.008975,-0.004866,-0.033424,-0.189458,-0.180899,-0.049443,0.072521,-0.069239,0.202837,0.090068,0.071074,-0.085654,-0.274147,0.016528,0.045599,0.093190,0.245543,-0.007048,-0.260234,-0.133390,0.046965,-0.083575,0.195281,-0.214088,0.114310,-0.290914,0.075791,-0.182935,0.296138,0.103445,...,0.544221,-0.360423,0.208056,0.311940,0.057003,0.020188,-0.221958,0.073712,-0.020183,0.448258,-0.059137,-0.194672,0.165183,0.026193,-0.387327,0.324638,0.130576,-0.000803,0.039415,0.007821,-0.051271,-0.078619,0.169500,0.091873,-0.128178,0.163870,-0.297129,0.246026,0.214468,-0.136142,-0.128801,-0.175998,0.109642,-0.068736,0.190212,-0.180588,0.214342,-0.124051,-0.300908,-0.076737
4,-0.041897,-0.128232,-0.096629,-0.068780,0.078374,-0.041795,0.128524,0.017905,0.171965,-0.143606,0.075063,0.139076,0.045531,0.021310,-0.311231,0.032365,-0.103571,-0.106746,0.117620,-0.059039,-0.245322,0.112892,0.001516,-0.199389,-0.078753,-0.255065,0.120610,0.168347,-0.006050,0.172317,0.154757,0.062209,-0.097490,0.121512,-0.127925,0.080865,0.044481,0.141599,0.044081,0.022964,...,0.405313,-0.064250,0.000319,0.014121,0.022538,-0.031398,-0.194104,0.060125,-0.121933,0.091883,0.039052,0.061282,0.054291,0.191105,-0.017288,0.138187,0.000548,0.134118,0.256910,-0.156446,0.020126,-0.202918,0.104911,0.121431,0.103637,0.057136,-0.043804,0.064853,-0.026075

In [4]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

,ido_tdo
0,AA
1,II
2,AI
3,II
4,II
...,...
755,II
756,II
757,IA
758,AI


In [5]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [6]:
X = df.iloc[:, :]
X

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,...,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383
0,0.098624,0.042223,-0.195243,0.209923,0.247522,-0.200116,0.130730,-0.078926,0.217784,-0.182055,-0.243452,-0.128551,0.014992,-0.187308,0.053134,0.172175,-0.036908,-0.089108,-0.158612,-0.175576,-0.147074,-0.137237,-0.023383,0.108736,0.110490,0.004352,0.199632,0.011544,0.247783,-0.131144,0.109549,-0.070373,0.081693,-0.004889,-0.073790,-0.009500,0.059168,-0.002304,0.099423,0.048033,...,0.397744,-0.058151,-0.222994,0.092650,0.015347,0.032601,-0.091596,-0.074980,0.016671,-0.099167,-0.033809,-0.046643,0.097833,0.106437,-0.127700,0.059653,0.046211,0.074801,0.136948,-0.043351,-0.009736,-0.101223,0.185495,0.222686,0.059982,0.096653,-0.290814,-0.072308,-0.047291,0.006758,-0.083785,-0.015257,0.208670,-0.099257,0.036652,0.011307,-0.015858,-0.034473,0.080340,0.090633
1,-0.195444,-0.006335,-0.125551,0.019175,-0.001245,-0.109488,0.118288,-0.345516,0.020197,-0.318505,-0.141652,-0.048505,0.051438,0.034231,-0.122795,0.134627,-0.019914,-0.224499,-0.282507,-0.006148,-0.334462,-0.077100,-0.352900,0.055391,-0.212135,0.235492,-0.005695,0.133163,0.104491,0.059605,-0.091889,-0.022493,-0.080808,0.118817,-0.063694,0.011782,-0.091441,0.021352,0.110410,-0.143980,...,0.105683,-0.098958,-0.164804,0.181757,0.200215,0.131650,0.201978,-0.216698,0.093964,-0.252054,0.098262,0.218040,-0.117740,-0.049576,0.287742,-0.153696,0.046452,-0.258802,-0.081757,0.196237,-0.283892,-0.056500,-0.063211,-0.007607,0.152183,-0.060643,-0.120640,-0.170838,0.012279,-0.124035,0.153339,-0.094293,0.072913,-0.126550,0.012802,-0.071275,0.245102,-0.169543,-0.080592,-0.355988
2,0.019954,0.011441,-0.158951,0.221017,0.246666,-0.214977,0.122784,-0.182540,0.290653,-0.235725,-0.271289,-0.122554,-0.024561,-0.165006,-0.047482,0.159697,-0.058642,-0.074084,-0.080705,-0.149393,-0.017351,-0.190900,-0.089300,0.130871,0.076236,-0.018202,0.064863,-0.064457,0.177324,-0.211699,0.038209,-0.179710,0.093308,-0.010702,-0.032118,0.066284,0.135030,-0.061713,0.082640,0.077583,...,0.363758,-0.120710,-0.277370,0.038140,0.104058,0.149905,-0.056109,-0.123888,0.014444,-0.059703,-0.029003,0.018654,0.167570,0.117122,-0.128163,-0.022087,0.023782,0.038430,0.181735,-0.018521,0.023721,-0.101120,0.183844,0.269394,-0.006547,0.232654,-0.292566,0.036904,-0.010980,-0.045801,-0.117349,-0.072634,0.212387,0.004530,-0.039211,-0.015519,0.015888,-0.153794,0.055760,0.118594
3,0.208809,0.168003,-0.015691,-0.009882,0.152641,0.031507,-0.038857,-0.054616,0.173442,-0.060251,-0.008975,-0.004866,-0.033424,-0.189458,-0.180899,-0.049443,0.072521,-0.069239,0.202837,0.090068,0.071074,-0.085654,-0.274147,0.016528,0.045599,0.093190,0.245543,-0.007048,-0.260234,-0.133390,0.046965,-0.083575,0.195281,-0.214088,0.114310,-0.290914,0.075791,-0.182935,0.296138,0.103445,...,0.544221,-0.360423,0.208056,0.311940,0.057003,0.020188,-0.221958,0.073712,-0.020183,0.448258,-0.059137,-0.194672,0.165183,0.026193,-0.387327,0.324638,0.130576,-0.000803,0.039415,0.007821,-0.051271,-0.078619,0.169500,0.091873,-0.128178,0.163870,-0.297129,0.246026,0.214468,-0.136142,-0.128801,-0.175998,0.109642,-0.068736,0.190212,-0.180588,0.214342,-0.124051,-0.300908,-0.076737
4,-0.041897,-0.128232,-0.096629,-0.068780,0.078374,-0.041795,0.128524,0.017905,0.171965,-0.143606,0.075063,0.139076,0.045531,0.021310,-0.311231,0.032365,-0.103571,-0.106746,0.117620,-0.059039,-0.245322,0.112892,0.001516,-0.199389,-0.078753,-0.255065,0.120610,0.168347,-0.006050,0.172317,0.154757,0.062209,-0.097490,0.121512,-0.127925,0.080865,0.044481,0.141599,0.044081,0.022964,...,0.405313,-0.064250,0.000319,0.014121,0.022538,-0.031398,-0.194104,0.060125,-0.121933,0.091883,0.039052,0.061282,0.054291,0.191105,-0.017288,0.138187,0.000548,0.134118,0.256910,-0.156446,0.020126,-0.202918,0.104911,0.121431,0.103637,0.057136,-0.043804,0.064853,-0.026075

In [7]:
X_scaled = StandardScaler().fit_transform(X)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, stratify=y, random_state=42 , test_size=0.2)

In [11]:
# using default values

clf = SVC(probability=True,kernel='rbf', random_state=42)

In [12]:
clf.fit(X_train, y_train)

SVC(probability=True, random_state=42)

In [13]:
ypred = clf.predict(X_test)

In [15]:
print("svm chemberta mtr")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred), roc_auc())

svm chemberta mtr
              precision    recall  f1-score   support

          AA       0.58      0.81      0.67        42
          AI       0.86      0.71      0.77        34
          IA       0.50      0.12      0.20        16
          II       0.77      0.78      0.78        60

    accuracy                           0.70       152
   macro avg       0.68      0.61      0.61       152
weighted avg       0.71      0.70      0.69       152

[[34  3  1  4]
 [ 6 24  0  4]
 [ 8  0  2  6]
 [11  1  1 47]] 0.8389445708839092


In [16]:
# using default values

clf = SVC(probability=True,kernel='linear', random_state=42)

In [17]:
clf.fit(X_train, y_train)

SVC(kernel='linear', probability=True, random_state=42)

In [18]:
ypred = clf.predict(X_test)

In [20]:
print("svm chemberta mtr kernel linear")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred), roc_auc())

svm chemberta mtr kernel linear
              precision    recall  f1-score   support

          AA       0.48      0.52      0.50        42
          AI       0.62      0.62      0.62        34
          IA       0.30      0.38      0.33        16
          II       0.71      0.62      0.66        60

    accuracy                           0.57       152
   macro avg       0.53      0.53      0.53       152
weighted avg       0.58      0.57      0.57       152

[[22  9  6  5]
 [ 7 21  1  5]
 [ 4  1  6  5]
 [13  3  7 37]] 0.8195193355119826


In [21]:
# using default values

clf = SVC(probability=True,kernel='rbf', random_state=42, class_weight='balanced')

In [22]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', probability=True, random_state=42)

In [27]:
ypred = clf.predict(X_test)

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
print("svm chemberta mtr rbf balanced")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred), roc_auc())

svm chemberta mtr rbf balanced
              precision    recall  f1-score   support

          AA       0.53      0.67      0.59        42
          AI       0.75      0.71      0.73        34
          IA       0.29      0.31      0.30        16
          II       0.80      0.67      0.73        60

    accuracy                           0.64       152
   macro avg       0.59      0.59      0.59       152
weighted avg       0.66      0.64      0.64       152

[[28  6  6  2]
 [ 6 24  0  4]
 [ 7  0  5  4]
 [12  2  6 40]] 0.8593567635387488


In [28]:
# using default values

clf = SVC(probability=True,kernel='linear', random_state=42 , class_weight='balanced')

In [29]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', kernel='linear', probability=True, random_state=42)

In [30]:
ypred = clf.predict(X_test)

In [31]:
print("svm chemberta mtr linear balanced")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred), roc_auc())

svm chemberta mtr linear balanced
              precision    recall  f1-score   support

          AA       0.59      0.57      0.58        42
          AI       0.60      0.62      0.61        34
          IA       0.29      0.38      0.32        16
          II       0.75      0.68      0.71        60

    accuracy                           0.61       152
   macro avg       0.55      0.56      0.56       152
weighted avg       0.62      0.61      0.61       152

[[24 10  5  3]
 [ 6 21  1  6]
 [ 4  1  6  5]
 [ 7  3  9 41]] 0.8165022953625894
