In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [3]:
def roc_auc():
    return roc_auc_score(y_test, clf.predict_proba(X_test) , multi_class='ovo')

In [4]:
df = pd.read_csv("maccskey_fp.csv")
df

,0,1,2,3,4,5,6,7,8,9,...,157,158,159,160,161,162,163,164,165,166
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
756,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0
757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0
758,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0


In [5]:
df_class = pd.read_csv("ido_tdo.csv" , index_col=0)
df_class

,ido_tdo
0,AA
1,II
2,AI
3,II
4,II
...,...
755,II
756,II
757,IA
758,AI


In [6]:
y = df_class.iloc[:,-1]
y

0      AA
1      II
2      AI
3      II
4      II
       ..
755    II
756    II
757    IA
758    AI
759    AA
Name: ido_tdo, Length: 760, dtype: object

In [7]:
X = df.iloc[:, :]
X

,0,1,2,3,4,5,6,7,8,9,...,157,158,159,160,161,162,163,164,165,166
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
756,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0
757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0
758,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0


In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y, random_state=42 , test_size=0.2)

In [12]:
clf = SVC(probability=True, kernel='rbf' , random_state=42)

In [13]:
clf.fit(X_train, y_train)

SVC(probability=True, random_state=42)

In [14]:
ypred = clf.predict(X_test)

In [16]:
print("svm maccskey")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
roc_auc()

svm maccskey
              precision    recall  f1-score   support

          AA       0.55      0.76      0.64        42
          AI       0.73      0.71      0.72        34
          IA       0.33      0.06      0.11        16
          II       0.79      0.77      0.78        60

    accuracy                           0.68       152
   macro avg       0.60      0.57      0.56       152
weighted avg       0.66      0.68      0.66       152

[[32  8  0  2]
 [ 6 24  0  4]
 [ 9  0  1  6]
 [11  1  2 46]]


np.float64(0.814196477201992)

In [17]:
clf = SVC(probability=True, kernel='linear' , random_state=42)

In [18]:
clf.fit(X_train, y_train)

SVC(kernel='linear', probability=True, random_state=42)

In [19]:
ypred = clf.predict(X_test)

In [21]:
print("svm maccskey linear")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
roc_auc()

svm maccskey linear
              precision    recall  f1-score   support

          AA       0.59      0.79      0.67        42
          AI       0.64      0.74      0.68        34
          IA       0.22      0.12      0.16        16
          II       0.79      0.63      0.70        60

    accuracy                           0.64       152
   macro avg       0.56      0.57      0.56       152
weighted avg       0.64      0.64      0.63       152

[[33  6  1  2]
 [ 7 25  0  2]
 [ 8  0  2  6]
 [ 8  8  6 38]]


np.float64(0.798348749221911)

In [22]:
clf = SVC(probability=True, kernel='rbf' , random_state=42 , class_weight='balanced')

In [23]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', probability=True, random_state=42)

In [24]:
ypred = clf.predict(X_test)

In [26]:
print("svm maccskey rbf balanced")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
roc_auc()

svm maccskey rbf balanced
              precision    recall  f1-score   support

          AA       0.57      0.69      0.62        42
          AI       0.72      0.76      0.74        34
          IA       0.25      0.31      0.28        16
          II       0.80      0.60      0.69        60

    accuracy                           0.63       152
   macro avg       0.59      0.59      0.58       152
weighted avg       0.66      0.63      0.64       152

[[29  8  4  1]
 [ 5 26  0  3]
 [ 6  0  5  5]
 [11  2 11 36]]


np.float64(0.8434197984749455)

In [27]:
clf = SVC(probability=True, kernel='linear' , random_state=42 , class_weight='balanced')

In [28]:
clf.fit(X_train, y_train)

SVC(class_weight='balanced', kernel='linear', probability=True, random_state=42)

In [29]:
ypred = clf.predict(X_test)

In [30]:
print("svm maccskey linear balanced")
print(classification_report(y_test , ypred))
print(confusion_matrix(y_test , ypred))
roc_auc()

svm maccskey linear balanced
              precision    recall  f1-score   support

          AA       0.57      0.69      0.62        42
          AI       0.67      0.76      0.71        34
          IA       0.27      0.38      0.32        16
          II       0.90      0.60      0.72        60

    accuracy                           0.64       152
   macro avg       0.60      0.61      0.59       152
weighted avg       0.69      0.64      0.65       152

[[29  6  7  0]
 [ 6 26  1  1]
 [ 7  0  6  3]
 [ 9  7  8 36]]


np.float64(0.8239362064270151)